### ISSUE TITLE
Container does not start

### ISSUE THREAD

**Issue by scottdrmyers** [Py-KMS-Organization/py-kms#102]
[Environment]

Intel 5105 CPU
16 GB DDR4
Ubuntu 22.04 with all latest updates
Docker
Portainer Business

[Docker Compose]

```
version: '3'

services:
  kms:
    image: ghcr.io/py-kms-organization/py-kms:python3
    ports:
      - 1688:1688
      - 46780:8080
    environment:
      IP: "::"
      HWID: RANDOM
      LOGLEVEL: INFO
    restart: always
    volumes:
      - ./db:/home/py-kms/db
      - /etc/localtime:/etc/localtime:ro
```

[Issue]

The container deploys and in Portainer I see that the ports are properly assigned. Then after about 10 seconds the ports disappear from Portainer in the container list, pykms is still showing as "running" but nothing is accessible clicking on the container name shows that the status is "restarting".

[Troubleshooting]

I deployed this on another docker host with the exact same configuration, although slightly different hardware. It runs without issues. 

[My Ask]

Wondering what I can look at to trouble shoot this. I tried changing the ports/leaving them at default, etc. No go. The ports are not consumed by any other container or service. Tried rebooting the machine as well. I've tried another ENV for the time:

TX: America/Halifax

Same issue.

I then deployed another pykms container "pykmsorg/py-kms" which works totally fine on 1688, however, this container has no webUI which is the whole purpose I wanted to switch to it. 

Any ideas?

Thanks!
