### ISSUE TITLE
Clients unable to activate again Py-KMS

### ISSUE THREAD

**Issue by dudefoxlive** [Py-KMS-Organization/py-kms#112]
Since the update on 05-26 my clients have been unable to activate against Py-KMS. Nothing has changed in my docker compose file. Logs show as if the clients aren't even able to contact Py-KMS container. 
```
---
version: "3"

services:
  py-kms:
    container_name: py-kms
    image: ghcr.io/py-kms-organization/py-kms:latest
    restart: unless-stopped
    ports:
      - 1688:1688/tcp
    environment:
      TZ: US/Eastern
      CLIENT_COUNT:
      LOGLEVEL: DEBUG
    volumes:
      - /etc/localtime:/etc/localtime:ro
```

![image](https://github.com/Py-KMS-Organization/py-kms/assets/50186495/8f0fb917-9a3c-48ec-a8b4-def455cd5d09)
