### ISSUE TITLE
Docker container not dropping privileges

### ISSUE THREAD

**Issue by gh0st-app1e** [Py-KMS-Organization/py-kms#37]
Docker container does not drop privileges and runs py-kms as root when started with docker compose in the following manner:
```
version: "3.9"

services:
  app:
    image: pykmsorg/py-kms:minimal
    ports:
      - 1688:1688
    volumes:
      - /etc/localtime:/etc/localtime:ro
```
The issue is also present when started with the way mentioned in README (`docker run -d --name py-kms --restart always -p 1688:1688 ghcr.io/py-kms-organization/py-kms`) and seems to be not related to docker itself but rather to `entrypoint.py`.

The following code https://github.com/Py-KMS-Organization/py-kms/blob/7f08d753e3bbc2ce6dda37a3593ae4f96832c112/docker/entrypoint.py#L29-L32 gets UID/GID from environment variables `UID` and `GID`. If they are not present, `os.getenv()` uses default values, making `new_uid` and `new_gid` equal to `uid` and `gid`, rendering checks https://github.com/Py-KMS-Organization/py-kms/blob/7f08d753e3bbc2ce6dda37a3593ae4f96832c112/docker/entrypoint.py#L39 and https://github.com/Py-KMS-Organization/py-kms/blob/7f08d753e3bbc2ce6dda37a3593ae4f96832c112/docker/entrypoint.py#L43 false, thus `os.setuid()` and `os.setgid()` are not called.
